# Azure pipeline for Terraform AKS module

pool:
  vmImage: 'ubuntu-latest'

variables:
  image_name: terraform-azurerm-aks:$(build.buildId)
  terraform_version: 0.12.10

stages:
- stage: build
  displayName: 'docker build'
  pr:
    branches:
      include:
        - '*'
  steps:
    - script: docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} -t ${IMAGE_NAME} .
    - script: docker run ${IMAGE_NAME} rake build

- stage: full
  displayName: 'docker run'
  trigger:
    - master
  steps:
    - script: docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} -t ${IMAGE_NAME} .
    - script: docker run ${IMAGE_NAME} rake full