# Azure pipeline for Terraform AKS module
pool:
  vmImage: 'ubuntu-latest'

variables:
  image_name: terraform-azurerm-aks:$(build.buildId)
  terraform_version: 0.12.10

jobs:
- job: build
  displayName: 'docker build'
  condition: and(eq(variables['Build.Reason'], 'PullRequest'))
    - master
  steps:
    - script: docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} -t ${IMAGE_NAME} .
    - script: docker run ${IMAGE_NAME} rake build

- job: full
  displayName: 'docker run'
  condition: and(eq(variables['build.sourceBranch'], 'refs/heads/master'))
  steps:
    - script: docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} -t ${IMAGE_NAME} .
    - script: docker run ${IMAGE_NAME} rake full