# Azure pipeline for Terraform AKS module

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imagename: terraform-azurerm-aks:$(build.buildId)

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker run -e "ARM_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID" -e "ARM_CLIENT_ID=$AZURE_CLIENT_ID" -e "ARM_CLIENT_SECRET=$AZURE_CLIENT_SECRET" -e "ARM_TENANT_ID=$AZURE_TENANT_ID" -e "ARM_TEST_LOCATION=WestUS2" -e "ARM_TEST_LOCATION_ALT=EastUS" --rm $(imageName) bash -c "./test.sh validate"
  displayName: 'docker run'