name: Update Changelog
on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

jobs:
  update-changelog:
    uses: Azure/tfmod-scaffold/.github/workflows/update-changelog.yaml@main